<a href="https://colab.research.google.com/github/Momo-1225/Momo/blob/gh-pages/Copy_of_APM466.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Template Bootstrap Function

In [5]:
yields = pd.read_csv("yield.csv")
forwards = pd.read_csv("forward.csv")
yields

0.062508801  -0.072344557  0.003124143  -0.019024706  -0.002817925  \
0    -0.007056     -0.003787     0.007561     -0.021387     -0.000473   
1    -0.008593     -0.001885    -0.010354     -0.010001     -0.002222   
2    -0.007224      0.000000     0.007573     -0.025150     -0.003053   
3    -0.008492      0.000000     0.010524     -0.024087     -0.001512   

   0.022554422  0.013466019  -0.021193797  -1.10E-01  
0     0.023351     0.049468     -0.042974  -0.004958  
1     0.034922     0.040438     -0.032885   0.019170  
2     0.037381     0.047488     -0.044191   0.013217  
3     0.037734     0.047835     -0.040615   0.015883

## Example Bond

In [6]:
forwards

-0.11119855  0.098434263  0.01404284  -0.025680305  0.002768576  \
0    -0.059290     0.048712    0.013553     -0.036431    -0.001779   
1    -0.044033     0.038138    0.010783     -0.029441    -0.003256   
2    -0.037043     0.028934    0.014574     -0.027065    -0.000967   

   0.026063542  0.097440297  0.071432254  0.016867423  
0     0.042365     0.056557    -0.040153     0.075431  
1     0.045738     0.064573    -0.057077     0.095499  
2     0.044547     0.061070    -0.049309     0.088726

## Bootstrapping spot rates

In [7]:
cov_y = np.cov(yields)
cov_f = np.cov(forwards)

cov_y

## Plotting the yield curve

In [9]:
cov_f

array([[0.00232621, 0.00243106, 0.00218089],
       [0.00243106, 0.00267522, 0.00241268],
       [0.00218089, 0.00241268, 0.00218489]])

In [22]:
eigenval_y, eigenvec_y = np.linalg.eig(cov_y)
eigenval_y
#eigenvec_y

array([[ 0.4845661 ,  0.64663776,  0.58527555,  0.06714046],
       [ 0.43375977, -0.76241844,  0.47804427,  0.04521336],
       [ 0.54253268,  0.02151999, -0.38748917, -0.74501498],
       [ 0.53170146,  0.01070604, -0.52799465,  0.66211826]])

In [23]:
eigenval_f, eigenvec_f = np.linalg.eig(cov_f)
eigenval_f
#eigenvec_f

array([7.09285047e-03, 8.96100771e-05, 3.86086990e-06])